---
title: "Polling"
author: "Elizabeth Guo"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(skimr)
library(fs)
library(purrr)
library(tidyverse)
library(broom)
```


```{r download, cache = TRUE}

download.file("https://github.com/TheUpshot/2018-live-poll-results/archive/master.zip", destfile = "master.zip")

unzip("master.zip")

# raw <- read_csv("2018-live-poll-results-master/data/elections-poll-az02-1.csv",
               # col_types = cols(
  #.default = col_character(),
  #turnout_scale = col_double(),
  #turnout_score = col_double(),
  #w_LV = col_double(),
  #w_RV = col_double(),
  #final_weight = col_double(),
  #timestamp = col_datetime(format = "")
#))

my_list <- fs::dir_ls("2018-live-poll-results-master/data/")

raw <- map_dfr(my_list, .id = "source", read_csv, col_types = cols(
  .default = col_character(),
  turnout_scale = col_double(),
  turnout_score = col_double(),
  w_LV = col_double(),
  w_RV = col_double(),
  final_weight = col_double(),
  timestamp = col_datetime(format = ""))
)

fs::file_delete(c("master.zip", "2018-live-poll-results-master/"))

```


```{r}
skim(raw)

```


# Summary of Raw Data

```{r}
x <- raw %>% 
  mutate(dvote = ifelse(response == "Dem", 1, 0)) %>% 
  mutate(female = ifelse(gender == "Female", 1, 0)) %>% 
  select(dvote, female, response, gender)


model <- glm(dvote ~ female, x, family = "binomial")
model
tidy(model)
glance(model)

x %>%
  ggplot(aes(x = female, y = dvote)) +
  geom_jitter() +
  geom_smooth(method = )


my_data <- tibble(female = c(0, 0, 1))

predict.glm(model, newdata = my_data, type = "response")

x_predictions <- x %>%
  mutate(prediction = predict(model, type = "response"))

x_predictions

```


